LIST_COMPILE= cube.geo bar.geo  tensile_crack.geo  bar_dynamic.geo quasistatic.geo  soil.geo L_shape.geo french_alps_two_volumes.geo
MESH_FILES  = cube.msh bar.msh tensile_crack.msh bar_dynamic.msh  quasistatic.msh  soil.msh L_shape.msh french_alps_two_volumes.msh

all-local: $(MESH_FILES)
	@echo ""
	@echo "*============================================================*"
	@echo " Creating 3D meshes in :"; pwd
	@echo "*============================================================*"
	@echo ""
	@echo " Mesh geo list: $(LIST_COMPILE)"

tensile_crack.msh: tensile_crack.geo
	$(GMSH) -3  tensile_crack.geo -o tensile_crack.msh -format msh2 -v 0
	@echo ""

quasistatic.msh: quasistatic.geo
	$(GMSH) -3 quasistatic.geo -o quasistatic.msh -format msh2 -v 0
	@echo ""

bar.msh: bar.geo
	$(GMSH) -3 bar.geo -o bar.msh -format msh2 -v 0
	@echo ""

cube.msh: cube.geo
	$(GMSH) -3 cube.geo -o cube.msh -format msh2 -clmin 0.5 -clmax 0.5 -v 0
	@echo ""

L_shape.msh: L_shape.geo
	$(GMSH) -3 L_shape.geo -o L_shape.msh -format msh2 -v 0
	@echo ""

bar_dynamic.msh: bar_dynamic.geo
	$(GMSH) -3 bar_dynamic.geo -o bar_dynamic.msh -format msh2 -v 0
	@echo ""

soil.msh: soil.geo
	$(GMSH) -3 soil.geo -o soil.msh -format msh2 -v 0
	$(GMSH) -1 soil.msh -o soil.msh -format msh2 -refine -v 0
	$(GMSH) -1 soil.msh -o soil.msh -format msh2 -refine -v 0
	$(GMSH) -1 soil.msh -o soil.msh -format msh2 -refine -v 0
	@echo ""

french_alps_two_volumes.msh: french_alps_two_volumes.geo
	$(GMSH) -3 french_alps_two_volumes.geo -o french_alps_two_volumes.msh -format msh2 -v 0
	@echo ""

copy-to-meshes:
	@mkdir -p ../Meshes
	@ls | egrep "^soil.msh" | xargs -I {} cp {} ../Meshes/.
	@ls | egrep "^bar.msh" | xargs -I {} cp {} ../Meshes/.
	@ls | egrep "^L_shape.msh" | xargs -I {} cp {} ../Meshes/.
	@ls | egrep "^quasistatic.msh" | xargs -I {} cp {} ../Meshes/.
	@ls | egrep "^bar_dynamic.msh" | xargs -I {} cp {} ../Meshes/.
	@ls | egrep "^tensile_crack.msh" | xargs -I {} cp {} ../Meshes/.
	@ls | egrep "^cube.msh" | xargs -I {} cp {} ../Meshes/.
	@ls | egrep "^french_alps_two_volumes.msh" | xargs -I {} cp {} ../Meshes/.

tutorials: copy-to-meshes


install-devel-local: copy-to-meshes

clean-local:
	@echo ""
	@echo "*============================================================*"
	@echo " Cleaning files in :"; pwd
	@echo "*============================================================*"
	@echo ""
	rm -f *~ *.msh *.med
	rm -rf ../Meshes
	@echo ""

distclean-local: clean-local
	@echo ""
	@echo "*============================================================*"
	@echo " Cleaning automake generated files"
	@echo "*============================================================*"
	@echo ""
	rm  -rf Makefile Makefile.in
